CREATE TABLE IF NOT EXISTS links (
    url TEXT PRIMARY KEY,
    origin TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visits INTEGER NOT NULL DEFAULT 0,
    secret TEXT NOT NULL
);